apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: open-webui
  name: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: open-webui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: open-webui
    spec:
      containers:
        - env:
            - name: OLLAMA_BASE_URL
              value: http://ollama.ollama.svc.cluster.local:11434
          image: ghcr.io/open-webui/open-webui:main
          name: open-webui
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: /app/backend/data
              name: open-webui
      restartPolicy: Always
      volumes:
        - name: open-webui
          persistentVolumeClaim:
            claimName: open-webui
  volumeClaimTemplates:
  - metadata:
      name: open-webui
      labels:
        app: open-webui
    spec:
      volumeMode: Filesystem
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
